on: [pull_request]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Clean up
        run: rm -rf *
      - uses: actions/checkout@v2
        with:
          path: 'meta-rust'
      - name: Fetch poky
        run: |
          git clone -b gatesgarth --single-branch git://git.yoctoproject.org/poky
          git clone -b gatesgarth --single-branch git://git.openembedded.org/meta-openembedded
      - name: Run bitbake
        run: |
          echo Build things
          cd poky
          . oe-init-build-env
          sed -i -e "\$i$(readlink -f ../../meta-openembedded/meta-oe) \\\\" conf/bblayers.conf
          sed -i -e "\$i$(readlink -f ../../meta-rust) \\\\" conf/bblayers.conf
          cat conf/bblayers.conf
          bitbake rust-hello-world
